name: Pipeline
on:
  push
jobs:
  test-oidc:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read
    steps:
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: tw-voxy-api-prod-848f
          workload_identity_provider: projects/839139424579/locations/global/workloadIdentityPools/github-actions-provider/providers/github-actions-provider
          service_account: github-actions@tw-voxy-api-prod-848f.iam.gserviceaccount.com
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: 'Verify that gcloud is authenticated'
        run: 'gcloud compute instances list' # please use the command which the affected service account’s permission allows to
